name: Deploy Marp Presentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # 必要に応じて Node.js のバージョンを指定

      - name: Install marp cli
        run: npm install -g @marp-team/marp-cli

      - name: Build
        run: marp

      - uses: actions/upload-pages-artifact@v3
        with:
          path: public


  deploy:
    needs: build
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
